services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "nayan123"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./treads-backend/backupfile.sql:/docker-entrypoint-initdb.d/backupfile.sql
    networks:
      - backend-network
    restart: unless-stopped

  backend:
    build: ./treads-backend
    depends_on:
      - db
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               gunicorn app.wsgi:application --workers=3 --bind=0.0.0.0:8000 --timeout=60"
    volumes:
      - ./treads-backend:/app
    networks:
      - backend-network
    restart: unless-stopped

  frontend:
    build: 
      context: ./treads-frontend
    # volumes:
    #   - ./treads-frontend:/app
    networks:
      - frontend-network
      - backend-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/main.conf:/etc/nginx/nginx.conf
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - frontend-network
      - backend-network
    restart: always

volumes:
  postgres_data:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge