# Generated by Django 5.1.6 on 2025-03-06 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aed',
            fields=[
                ('aedname', models.CharField(primary_key=True, serialize=False)),
                ('uniprotid', models.CharField(blank=True, null=True)),
                ('genename', models.CharField(blank=True, null=True)),
                ('drugbankid', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aed2',
            fields=[
                ('aedname', models.CharField(primary_key=True, serialize=False)),
                ('uniprotid', models.CharField()),
                ('drugbankid', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aed2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aed3',
            fields=[
                ('aedname', models.CharField(primary_key=True, serialize=False)),
                ('drugbankid', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aed3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aed4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aedname', models.CharField(blank=True, null=True)),
                ('uniprotid', models.CharField(blank=True, null=True)),
                ('genename', models.CharField(blank=True, null=True)),
                ('drugbankid', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aed4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drugtarget',
            fields=[
                ('uniprotid', models.CharField(primary_key=True, serialize=False)),
                ('genename', models.CharField(blank=True, null=True)),
                ('aed', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drugtarget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drugtarget3',
            fields=[
                ('uniprotid', models.CharField(primary_key=True, serialize=False)),
                ('genename', models.CharField(blank=True, null=True)),
                ('aed', models.CharField()),
            ],
            options={
                'db_table': 'drugtarget3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrugtargetBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprotid', models.CharField(blank=True, null=True)),
                ('genename', models.CharField(blank=True, null=True)),
                ('aed', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drugtarget_backup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('uniprotid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('genename', models.CharField(blank=True, max_length=50, null=True)),
                ('uniprotname', models.CharField(blank=True, max_length=50, null=True)),
                ('protein_name', models.TextField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('a', models.IntegerField(blank=True, null=True)),
                ('c', models.IntegerField(blank=True, null=True)),
                ('d', models.IntegerField(blank=True, null=True)),
                ('e', models.IntegerField(blank=True, null=True)),
                ('f', models.IntegerField(blank=True, null=True)),
                ('g', models.IntegerField(blank=True, null=True)),
                ('h', models.IntegerField(blank=True, null=True)),
                ('i', models.IntegerField(blank=True, null=True)),
                ('k', models.IntegerField(blank=True, null=True)),
                ('l', models.IntegerField(blank=True, null=True)),
                ('m', models.IntegerField(blank=True, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
                ('p', models.IntegerField(blank=True, null=True)),
                ('q', models.IntegerField(blank=True, null=True)),
                ('r', models.IntegerField(blank=True, null=True)),
                ('s', models.IntegerField(blank=True, null=True)),
                ('t', models.IntegerField(blank=True, null=True)),
                ('v', models.IntegerField(blank=True, null=True)),
                ('w', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('sequence', models.TextField(blank=True, null=True)),
                ('bgeeid', models.CharField(blank=True, max_length=20, null=True)),
                ('organexpression', models.CharField(blank=True, max_length=500, null=True)),
                ('nlinkedglycosylation', models.IntegerField(blank=True, null=True)),
                ('olinkedglycosylation', models.IntegerField(blank=True, null=True)),
                ('phosphoserine', models.IntegerField(blank=True, null=True)),
                ('phosphothreonine', models.IntegerField(blank=True, null=True)),
                ('phosphotyrosine', models.IntegerField(blank=True, null=True)),
                ('hydrophobicity', models.FloatField(blank=True, null=True)),
                ('lcr', models.CharField(blank=True, max_length=10, null=True)),
                ('isoelectricpoint', models.FloatField(blank=True, null=True)),
                ('alphahelix', models.FloatField(blank=True, null=True)),
                ('betastrand', models.FloatField(blank=True, null=True)),
                ('coils', models.FloatField(blank=True, null=True)),
                ('pestmotifs', models.FloatField(blank=True, null=True)),
                ('brainexpression', models.CharField(blank=True, max_length=5, null=True)),
                ('drugtarget', models.CharField(blank=True, max_length=5, null=True)),
                ('supportvectormachine', models.CharField(blank=True, max_length=5, null=True)),
                ('gradientboosting', models.CharField(blank=True, max_length=5, null=True)),
                ('randomforestclassifier', models.CharField(blank=True, max_length=5, null=True)),
                ('multilayerperceptron', models.CharField(blank=True, max_length=5, null=True)),
                ('signal_peptide', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'features',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniprotAed',
            fields=[
                ('uniprotid', models.OneToOneField(db_column='uniprotid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='epilepsy.features')),
            ],
            options={
                'db_table': 'uniprot_aed',
                'managed': False,
            },
        ),
    ]
