const JmeJsonData = {
  data: [
    {
      uniprotID: 'B3EWF7',
      gene: 'EPM2A',
      proteinName: 'Laforin, isoform 9',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'O00305',
      gene: 'CACNB4',
      proteinName: 'Voltage-dependent L-type calcium channel subunit beta-4',
      reference: 'PMID: 23756480   PMID: 29924869',
    },
    {
      uniprotID: 'O00555',
      gene: 'CACNA1A',
      proteinName:
        'Voltage-dependent P/Q-type calcium channel subunit alpha-1A',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'O14647',
      gene: 'CHD2',
      proteinName: 'Chromodomain-helicase-DNA-binding protein 2',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'O14764',
      gene: 'GABRD',
      proteinName: 'Gamma-aminobutyric acid receptor subunit delta',
      reference: 'PMID: 23756480   PMID: 29924869',
    },
    {
      uniprotID: 'O14773',
      gene: 'TPP1',
      proteinName: 'Tripeptidyl-peptidase 1',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'O43497',
      gene: 'CACNA1G',
      proteinName: 'Voltage-dependent T-type calcium channel subunit alpha-1G',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'O43525',
      gene: 'KCNQ3',
      proteinName: 'Potassium voltage-gated channel subfamily KQT member 3',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'O43766',
      gene: 'LIAS',
      proteinName: 'Lipoyl synthase, mitochondrial',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'O60315',
      gene: 'ZEB2',
      proteinName: 'Zinc finger E-box-binding homeobox 2',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'O75564',
      gene: 'JRK',
      proteinName: 'Jerky protein homolog',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'O95180',
      gene: 'CACNA1H',
      proteinName: 'Voltage-dependent T-type calcium channel subunit alpha-1H',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'O95970',
      gene: 'LGI1',
      proteinName: 'Leucine-rich glioma-inactivated protein 1',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'P14867',
      gene: 'GABRA1',
      proteinName: 'Gamma-aminobutyric acid receptor subunit alpha-1',
      reference: 'PMID: 23756480',
    },
    {
      uniprotID: 'P15328',
      gene: 'FOLR1',
      proteinName: 'Folate receptor alpha',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'P17787',
      gene: 'CHRNB2',
      proteinName: 'Neuronal acetylcholine receptor subunit beta-2',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'P23368',
      gene: 'ME2',
      proteinName: 'NAD-dependent malic enzyme, mitochondrial',
      reference: 'PMID: 23756480   PMID: 29924869',
    },
    {
      uniprotID: 'P25440',
      gene: 'BRD2',
      proteinName: 'Bromodomain-containing protein 2',
      reference: 'PMID: 23756480',
    },
    {
      uniprotID: 'P28472',
      gene: 'GABRB3',
      proteinName: 'Gamma-aminobutyric acid receptor subunit beta-3',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'P35372',
      gene: 'OPRM1',
      proteinName: 'Mu-type opioid receptor',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'P35498',
      gene: 'SCN1A',
      proteinName: 'Sodium channel protein type 1 subunit alpha',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'P36544',
      gene: 'CHRNA7',
      proteinName: 'Neuronal acetylcholine receptor subunit alpha-7',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'P41180',
      gene: 'CASR',
      proteinName: 'Extracellular calcium-sensing receptor',
      reference: 'PMID: 23756480   PMID: 29924869',
    },
    {
      uniprotID: 'P43681',
      gene: 'CHRNA4',
      proteinName: 'Neuronal acetylcholine receptor subunit alpha-4',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'P48165',
      gene: 'GJA8',
      proteinName: 'Gap junction alpha-8 protein',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'P49419',
      gene: 'ALDH7A1',
      proteinName: 'Alpha-aminoadipic semialdehyde dehydrogenase',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'P50440',
      gene: 'GATM',
      proteinName: 'Glycine amidinotransferase, mitochondrial',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'P51788',
      gene: 'CLCN2',
      proteinName: 'Chloride channel protein 2',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'P61764',
      gene: 'STXBP1',
      proteinName: 'Syntaxin-binding protein 1',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q05086',
      gene: 'UBE3A',
      proteinName: 'Ubiquitin-protein ligase E3A',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q05901',
      gene: 'CHRNB3',
      proteinName: 'Neuronal acetylcholine receptor subunit beta-3',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q07699',
      gene: 'SCN1B',
      proteinName: 'Sodium channel subunit beta-1',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q12791',
      gene: 'KCNMA1',
      proteinName: 'Calcium-activated potassium channel subunit alpha-1',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q12879',
      gene: 'GRIN2A',
      proteinName: 'Glutamate receptor ionotropic, NMDA 2A',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q13813',
      gene: 'SPTAN1',
      proteinName: 'Spectrin alpha chain, non-erythrocytic 1',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q14833',
      gene: 'GRM4',
      proteinName: 'Metabotropic glutamate receptor 4',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q15822',
      gene: 'CHRNA2',
      proteinName: 'Neuronal acetylcholine receptor subunit alpha-2',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q15858',
      gene: 'SCN9A',
      proteinName: 'Sodium channel protein type 9 subunit alpha',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q5JST6',
      gene: 'EFHC2',
      proteinName: 'EF-hand domain-containing family member C2',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q5JVL4',
      gene: 'EFHC1',
      proteinName: 'EF-hand domain-containing protein 1',
      reference: 'PMID: 23756480   PMID: 29924869',
    },
    {
      uniprotID: 'Q5M775',
      gene: 'SPECC1',
      proteinName: 'Cytospin-B',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q5T011',
      gene: 'SZT2',
      proteinName: 'KICSTOR complex protein SZT2',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q7Z6L0',
      gene: 'PRRT2',
      proteinName: 'Proline-rich transmembrane protein 2',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q8N135',
      gene: 'LGI4',
      proteinName: 'Leucine-rich repeat LGI family member 4',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q8N4T0',
      gene: 'CPA6',
      proteinName: 'Carboxypeptidase A6',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q8NHS3',
      gene: 'MFSD8',
      proteinName: 'Major facilitator superfamily domain-containing protein 8',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q8TAB3',
      gene: 'PCDH19',
      proteinName: 'Protocadherin-19',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q96MT3',
      gene: 'PRICKLE1',
      proteinName: 'Prickle-like protein 1',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q96QS3',
      gene: 'ARX',
      proteinName: 'Homeobox protein ARX',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q96T60',
      gene: 'PNKP',
      proteinName: 'Bifunctional polynucleotide phosphatase/kinase',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q99250',
      gene: 'SCN2A',
      proteinName: 'Sodium channel protein type 2 subunit alpha',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q9H936',
      gene: 'SLC25A22',
      proteinName: 'Mitochondrial glutamate carrier 1',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q9NXR1',
      gene: 'NDE1',
      proteinName: 'Nuclear distribution protein nudE homolog 1',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q9NY46',
      gene: 'SCN3A',
      proteinName: 'Sodium channel protein type 3 subunit alpha',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q9ULB1',
      gene: 'NRXN1',
      proteinName: 'Neurexin-1',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q9ULP9',
      gene: 'TBC1D24',
      proteinName: 'TBC1 domain family member 24',
      reference: 'PMID: 29924869',
    },
    {
      uniprotID: 'Q9UQD0',
      gene: 'SCN8A',
      proteinName: 'Sodium channel protein type 8 subunit alpha',
      reference: 'PMID: 29924869',
    },
  ],
};

export default JmeJsonData;
