services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "nayan123"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backupfile.sql:/docker-entrypoint-initdb.d/backupfile.sql  # Mount backup.sql

  backend:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
volumes:
  postgres_data: