const MtleJsonData = {
  data: [
    {
      uniprotID: 'A2IDD5',
      gene: 'CCDC78',
      proteinName: 'Coiled-coil domain-containing protein 78',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'A5D8T8',
      gene: 'CLEC18A',
      proteinName: 'C-type lectin domain family 18 member A',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'A6NCJ1',
      gene: 'C19orf71',
      proteinName: 'Uncharacterized protein C19orf71',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'A6NDP7',
      gene: 'MYADML2',
      proteinName: 'Myeloid-associated differentiation marker-like protein 2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'A6NEQ0',
      gene: 'RBMY1E',
      proteinName: 'RNA-binding motif protein, Y chromosome, family 1 member E',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'A6NGY3',
      gene: 'C5orf52',
      proteinName: 'Uncharacterized protein C5orf52',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'A6NHC0',
      gene: 'CAPN8',
      proteinName: 'Calpain-8',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'A6NI86',
      gene: 'GOLGA6L10',
      proteinName: 'Golgin subfamily A member 6-like protein 10',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'A6NK44',
      gene: 'GLOD5',
      proteinName: 'Glyoxalase domain-containing protein 5',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'B1AJZ9',
      gene: 'FHAD1',
      proteinName: 'Forkhead-associated domain-containing protein 1',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'B2RN74',
      gene: 'OR11H12',
      proteinName: 'Olfactory receptor 11H12',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'O00238',
      gene: 'BMPR1B',
      proteinName: 'Bone morphogenetic protein receptor type-1B',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'O00339',
      gene: 'MATN2',
      proteinName: 'Matrilin-2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'O00408',
      gene: 'PDE2A',
      proteinName: "cGMP-dependent 3',5'-cyclic phosphodiesterase",
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'O00541',
      gene: 'PES1',
      proteinName: 'Pescadillo homolog',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'O15120',
      gene: 'AGPAT2',
      proteinName: '1-acyl-sn-glycerol-3-phosphate acyltransferase beta',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'O15342',
      gene: 'ATP6V0E1',
      proteinName: 'V-type proton ATPase subunit e 1',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'O15393',
      gene: 'TMPRSS2',
      proteinName: 'Transmembrane protease serine 2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'O15417',
      gene: 'TNRC18',
      proteinName: 'Trinucleotide repeat-containing gene 18 protein',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'O15482',
      gene: 'TEX28',
      proteinName: 'Testis-specific protein TEX28',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'O15547',
      gene: 'P2RX6',
      proteinName: 'P2X purinoceptor 6',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'O43278',
      gene: 'SPINT1',
      proteinName: 'Kunitz-type protease inhibitor 1',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'O43439',
      gene: 'CBFA2T2',
      proteinName: 'Protein CBFA2T2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'O43927',
      gene: 'CXCL13',
      proteinName: 'C-X-C motif chemokine 13',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'O60235',
      gene: 'TMPRSS11D',
      proteinName: 'Transmembrane protease serine 11D',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'O60462',
      gene: 'NRP2',
      proteinName: 'Neuropilin-2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'O60575',
      gene: 'SPINK4',
      proteinName: 'Serine protease inhibitor Kazal-type 4',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'O60658',
      gene: 'PDE8A',
      proteinName:
        "High affinity cAMP-specific and IBMX-insensitive 3',5'-cyclic phosphodiesterase 8A",
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'O75508',
      gene: 'CLDN11',
      proteinName: 'Claudin-11',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'O75575',
      gene: 'CRCP',
      proteinName: 'DNA-directed RNA polymerase III subunit RPC9',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'O75602',
      gene: 'SPAG6',
      proteinName: 'Sperm-associated antigen 6',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'O75899',
      gene: 'GABBR2',
      proteinName: 'Gamma-aminobutyric acid type B receptor subunit 2',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'O75914',
      gene: 'PAK3',
      proteinName: 'Serine/threonine-protein kinase PAK 3',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'O95359',
      gene: 'TACC2',
      proteinName: 'Transforming acidic coiled-coil-containing protein 2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'O95670',
      gene: 'ATP6V1G2',
      proteinName: 'V-type proton ATPase subunit G 2',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'O95678',
      gene: 'KRT75',
      proteinName: 'Keratin, type II cytoskeletal 75',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'O95970',
      gene: 'LGI1',
      proteinName: 'Leucine-rich glioma-inactivated protein 1',
      reference: 'PMID: 28007376',
    },
    {
      uniprotID: 'P00568',
      gene: 'AK1',
      proteinName: 'Adenylate kinase isoenzyme 1',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P01589',
      gene: 'IL2RA',
      proteinName: 'Interleukin-2 receptor subunit alpha',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P01903',
      gene: 'HLA-DRA',
      proteinName: 'HLA class II histocompatibility antigen, DR alpha chain',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P01909',
      gene: 'HLA-DQA1',
      proteinName: 'HLA class II histocompatibility antigen, DQ alpha 1 chain',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P01911',
      gene: 'HLA-DRB1',
      proteinName:
        'HLA class II histocompatibility antigen, DRB1-15 beta chain',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P02452',
      gene: 'COL1A1',
      proteinName: 'Collagen alpha-1(I) chain',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P02461',
      gene: 'COL3A1',
      proteinName: 'Collagen alpha-1(III) chain',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P02489',
      gene: 'CRYAA',
      proteinName: 'Alpha-crystallin A chain',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P02679',
      gene: 'FGG',
      proteinName: 'Fibrinogen gamma chain',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P02775',
      gene: 'PPBP',
      proteinName: 'Platelet basic protein',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P02776',
      gene: 'PF4',
      proteinName: 'Platelet factor 4',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P04233',
      gene: 'CD74',
      proteinName: 'HLA class II histocompatibility antigen gamma chain',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P05771',
      gene: 'PRKCB',
      proteinName: 'Protein kinase C beta type',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P06340',
      gene: 'HLA-DOA',
      proteinName: 'HLA class II histocompatibility antigen, DO alpha chain',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P07333',
      gene: 'CSF1R',
      proteinName: 'Macrophage colony-stimulating factor 1 receptor',
      reference: 'PMID: 30177815',
    },
    {
      uniprotID: 'P07476',
      gene: 'IVL',
      proteinName: 'Involucrin',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P07498',
      gene: 'CSN3',
      proteinName: 'Kappa-casein',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P08684',
      gene: 'CYP3A4',
      proteinName: 'Cytochrome P450 3A4',
      reference: 'PMID: 28276448',
    },
    {
      uniprotID: 'P08865',
      gene: 'RPSA',
      proteinName: '40S ribosomal protein SA',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P09017',
      gene: 'HOXC4',
      proteinName: 'Homeobox protein Hox-C4',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P09430',
      gene: 'TNP1',
      proteinName: 'Spermatid nuclear transition protein 1',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P0CG48',
      gene: 'UBC',
      proteinName: 'Polyubiquitin-C',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P0DML2',
      gene: 'CSH1',
      proteinName: 'Chorionic somatomammotropin hormone 1',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P0DMV8',
      gene: 'HSPA1A',
      proteinName: 'Heat shock 70 kDa protein 1A',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P0DP25',
      gene: 'CALM3',
      proteinName: 'Calmodulin-3',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P11488',
      gene: 'GNAT1',
      proteinName: 'Guanine nucleotide-binding protein G(t) subunit alpha-1',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P11712',
      gene: 'CYP2C9',
      proteinName: 'Cytochrome P450 2C9',
      reference: 'PMID: 28276448',
    },
    {
      uniprotID: 'P12110',
      gene: 'COL6A2',
      proteinName: 'Collagen alpha-2(VI) chain',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P12814',
      gene: 'ACTN1',
      proteinName: 'Alpha-actinin-1',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P13500',
      gene: 'CCL2',
      proteinName: 'C-C motif chemokine 2',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P13747',
      gene: 'HLA-E',
      proteinName: 'HLA class I histocompatibility antigen, alpha chain E',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P15918',
      gene: 'RAG1',
      proteinName: 'V(D)J recombination-activating protein 1',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P16144',
      gene: 'ITGB4',
      proteinName: 'Integrin beta-4',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P16401',
      gene: 'HIST1H1B',
      proteinName: 'Histone H1.5',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P17081',
      gene: 'RHOQ',
      proteinName: 'Rho-related GTP-binding protein RhoQ',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P17538',
      gene: 'CTRB1',
      proteinName: 'Chymotrypsinogen B',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P17540',
      gene: 'CKMT2',
      proteinName: 'Creatine kinase S-type, mitochondrial',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P17655',
      gene: 'CAPN2',
      proteinName: 'Calpain-2 catalytic subunit',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P18505',
      gene: 'GABRB1',
      proteinName: 'Gamma-aminobutyric acid receptor subunit beta-1',
      reference: 'PMID: 28276448',
    },
    {
      uniprotID: 'P18507',
      gene: 'GABRG2',
      proteinName: 'Gamma-aminobutyric acid receptor subunit gamma-2',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P18564',
      gene: 'ITGB6',
      proteinName: 'Integrin beta-6',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P19971',
      gene: 'TYMP',
      proteinName: 'Thymidine phosphorylase',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P20036',
      gene: 'HLA-DPA1',
      proteinName: 'HLA class II histocompatibility antigen, DP alpha 1 chain',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P20851',
      gene: 'C4BPB',
      proteinName: 'C4b-binding protein beta chain',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P21549',
      gene: 'AGXT',
      proteinName: 'Serine--pyruvate aminotransferase',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P22466',
      gene: 'GAL',
      proteinName: 'Galanin peptides',
      reference: 'PMID: 28007376',
    },
    {
      uniprotID: 'P25963',
      gene: 'NFKBIA',
      proteinName: 'NF-kappa-B inhibitor alpha',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P26368',
      gene: 'U2AF2',
      proteinName: 'Splicing factor U2AF 65 kDa subunit',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P27635',
      gene: 'RPL10',
      proteinName: '60S ribosomal protein L10',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P28223',
      gene: 'HTR2A',
      proteinName: '5-hydroxytryptamine receptor 2A',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P28472',
      gene: 'GABRB3',
      proteinName: 'Gamma-aminobutyric acid receptor subunit beta-3',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P28482',
      gene: 'MAPK1',
      proteinName: 'Mitogen-activated protein kinase 1',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P30041',
      gene: 'PRDX6',
      proteinName: 'Peroxiredoxin-6',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P30939',
      gene: 'HTR1F',
      proteinName: '5-hydroxytryptamine receptor 1F',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P31260',
      gene: 'HOXA10',
      proteinName: 'Homeobox protein Hox-A10',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P31271',
      gene: 'HOXA13',
      proteinName: 'Homeobox protein Hox-A13',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P31323',
      gene: 'PRKAR2B',
      proteinName:
        'cAMP-dependent protein kinase type II-beta regulatory subunit',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P31350',
      gene: 'RRM2',
      proteinName: 'Ribonucleoside-diphosphate reductase subunit M2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P31644',
      gene: 'GABRA5',
      proteinName: 'Gamma-aminobutyric acid receptor subunit alpha-5',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P35354',
      gene: 'PTGS2',
      proteinName: 'Prostaglandin G/H synthase 2',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P35916',
      gene: 'FLT4',
      proteinName: 'Vascular endothelial growth factor receptor 3',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P36222',
      gene: 'CHI3L1',
      proteinName: 'Chitinase-3-like protein 1',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P36952',
      gene: 'SERPINB5',
      proteinName: 'Serpin B5',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P36959',
      gene: 'GMPR',
      proteinName: 'GMP reductase 1',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P37088',
      gene: 'SCNN1A',
      proteinName: 'Amiloride-sensitive sodium channel subunit alpha',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P37802',
      gene: 'TAGLN2',
      proteinName: 'Transgelin-2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P40199',
      gene: 'CEACAM6',
      proteinName: 'Carcinoembryonic antigen-related cell adhesion molecule 6',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P41220',
      gene: 'RGS2',
      proteinName: 'Regulator of G-protein signaling 2',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P41222',
      gene: 'PTGDS',
      proteinName: 'Prostaglandin-H2 D-isomerase',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P41594',
      gene: 'GRM5',
      proteinName: 'Metabotropic glutamate receptor 5',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P42261',
      gene: 'GRIA1',
      proteinName: 'Glutamate receptor 1',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P42262',
      gene: 'GRIA2',
      proteinName: 'Glutamate receptor 2',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P42263',
      gene: 'GRIA3',
      proteinName: 'Glutamate receptor 3',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P42330',
      gene: 'AKR1C3',
      proteinName: 'Aldo-keto reductase family 1 member C3',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P45985',
      gene: 'MAP2K4',
      proteinName: 'Dual specificity mitogen-activated protein kinase kinase 4',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P46459',
      gene: 'NSF',
      proteinName: 'Vesicle-fusing ATPase',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P47869',
      gene: 'GABRA2',
      proteinName: 'Gamma-aminobutyric acid receptor subunit alpha-2',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P49418',
      gene: 'AMPH',
      proteinName: 'Amphiphysin',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P49768',
      gene: 'PSEN1',
      proteinName: 'Presenilin-1',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P49798',
      gene: 'RGS4',
      proteinName: 'Regulator of G-protein signaling 4',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P49802',
      gene: 'RGS7',
      proteinName: 'Regulator of G-protein signaling 7',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P51116',
      gene: 'FXR2',
      proteinName: 'Fragile X mental retardation syndrome-related protein 2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P51160',
      gene: 'PDE6C',
      proteinName:
        "Cone cGMP-specific 3',5'-cyclic phosphodiesterase subunit alpha'",
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P51532',
      gene: 'SMARCA4',
      proteinName: 'Transcription activator BRG1',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P51797',
      gene: 'CLCN6',
      proteinName: 'Chloride transport protein 6',
      reference: 'PMID: 28276448',
    },
    {
      uniprotID: 'P51828',
      gene: 'ADCY7',
      proteinName: 'Adenylate cyclase type 7',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P53041',
      gene: 'PPP5C',
      proteinName: 'Serine/threonine-protein phosphatase 5',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P54315',
      gene: 'PNLIPRP1',
      proteinName: 'Inactive pancreatic lipase-related protein 1',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P54803',
      gene: 'GALC',
      proteinName: 'Galactocerebrosidase',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P56202',
      gene: 'CTSW',
      proteinName: 'Cathepsin W',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P56279',
      gene: 'TCL1A',
      proteinName: 'T-cell leukemia/lymphoma protein 1A',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P57730',
      gene: 'CARD18',
      proteinName: 'Caspase recruitment domain-containing protein 18',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P61073',
      gene: 'CXCR4',
      proteinName: 'C-X-C chemokine receptor type 4',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P61204',
      gene: 'ARF3',
      proteinName: 'ADP-ribosylation factor 3',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P61371',
      gene: 'ISL1',
      proteinName: 'Insulin gene enhancer protein ISL-1',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P63104',
      gene: 'YWHAZ',
      proteinName: '14-3-3 protein zeta/delta',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P78352',
      gene: 'DLG4',
      proteinName: 'Disks large homolog 4',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P78385',
      gene: 'KRT83',
      proteinName: 'Keratin, type II cuticular Hb3',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P78545',
      gene: 'ELF3',
      proteinName: 'ETS-related transcription factor Elf-3',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'P79483',
      gene: 'HLA-DRB3',
      proteinName: 'HLA class II histocompatibility antigen, DR beta 3 chain',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'P98173',
      gene: 'FAM3A',
      proteinName: 'Protein FAM3A',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q00887',
      gene: 'PSG9',
      proteinName: 'Pregnancy-specific beta-1-glycoprotein 9',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q01804',
      gene: 'OTUD4',
      proteinName: 'OTU domain-containing protein 4',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q02086',
      gene: 'SP2',
      proteinName: 'Transcription factor Sp2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q03112',
      gene: 'MECOM',
      proteinName: 'Histone-lysine N-methyltransferase MECOM',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q05193',
      gene: 'DNM1',
      proteinName: 'Dynamin-1',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'Q05586',
      gene: 'GRIN1',
      proteinName: 'Glutamate receptor ionotropic, NMDA 1',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'Q06710',
      gene: 'PAX8',
      proteinName: 'Paired box protein Pax-8',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q07687',
      gene: 'DLX2',
      proteinName: 'Homeobox protein DLX-2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q08477',
      gene: 'CYP4F3',
      proteinName: 'Cytochrome P450 4F3',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'Q08752',
      gene: 'PPID',
      proteinName: 'Peptidyl-prolyl cis-trans isomerase D',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q13017',
      gene: 'ARHGAP5',
      proteinName: 'Rho GTPase-activating protein 5',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'Q13115',
      gene: 'DUSP4',
      proteinName: 'Dual specificity protein phosphatase 4',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'Q13822',
      gene: 'ENPP2',
      proteinName:
        'Ectonucleotide pyrophosphatase/phosphodiesterase family member 2',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'Q13938',
      gene: 'CAPS',
      proteinName: 'Calcyphosin',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q14289',
      gene: 'PTK2B',
      proteinName: 'Protein-tyrosine kinase 2-beta',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'Q14526',
      gene: 'HIC1',
      proteinName: 'Hypermethylated in cancer 1 protein',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q14CN2',
      gene: 'CLCA4',
      proteinName: 'Calcium-activated chloride channel regulator 4',
      reference: 'PMID: 28276448',
    },
    {
      uniprotID: 'Q15063',
      gene: 'POSTN',
      proteinName: 'Periostin',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q15398',
      gene: 'DLGAP5',
      proteinName: 'Disks large-associated protein 5',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q15562',
      gene: 'TEAD2',
      proteinName: 'Transcriptional enhancer factor TEF-4',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q15699',
      gene: 'ALX1',
      proteinName: 'ALX homeobox protein 1',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q16363',
      gene: 'LAMA4',
      proteinName: 'Laminin subunit alpha-4',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'Q16828',
      gene: 'DUSP6',
      proteinName: 'Dual specificity protein phosphatase 6',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'Q16880',
      gene: 'UGT8',
      proteinName: '2-hydroxyacylsphingosine 1-beta-galactosyltransferase',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'Q17RY6',
      gene: 'LY6K',
      proteinName: 'Lymphocyte antigen 6K',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q2M3G0',
      gene: 'ABCB5',
      proteinName: 'ATP-binding cassette sub-family B member 5',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q2TAC2',
      gene: 'CCDC57',
      proteinName: 'Coiled-coil domain-containing protein 57',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q33E94',
      gene: 'RFX4',
      proteinName: 'Transcription factor RFX4',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q3LI67',
      gene: 'KRTAP6-3',
      proteinName: 'Keratin-associated protein 6-3',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q3MIR4',
      gene: 'TMEM30B',
      proteinName: 'Cell cycle control protein 50B',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q4VXF1',
      gene: 'FAM74A3',
      proteinName: 'Putative protein FAM74A3',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q58EX2',
      gene: 'SDK2',
      proteinName: 'Protein sidekick-2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q5GH73',
      gene: 'XKR6',
      proteinName: 'XK-related protein 6',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q5JSP0',
      gene: 'FGD3',
      proteinName: 'FYVE, RhoGEF and PH domain-containing protein 3',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q5SVZ6',
      gene: 'ZMYM1',
      proteinName: 'Zinc finger MYM-type protein 1',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q5W041',
      gene: 'ARMC3',
      proteinName: 'Armadillo repeat-containing protein 3',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q66K79',
      gene: 'CPZ',
      proteinName: 'Carboxypeptidase Z',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q6DN12',
      gene: 'MCTP2',
      proteinName: 'Multiple C2 and transmembrane domain-containing protein 2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q6KCM7',
      gene: 'SLC25A25',
      proteinName: 'Calcium-binding mitochondrial carrier protein SCaMC-2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q6NT55',
      gene: 'CYP4F22',
      proteinName: 'Cytochrome P450 4F22',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q6P1N0',
      gene: 'CC2D1A',
      proteinName: 'Coiled-coil and C2 domain-containing protein 1A',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q6P9F0',
      gene: 'CCDC62',
      proteinName: 'Coiled-coil domain-containing protein 62',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q6PI97',
      gene: 'C11orf88',
      proteinName: 'UPF0722 protein C11orf88',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q6PIS1',
      gene: 'SLC23A3',
      proteinName: 'Solute carrier family 23 member 3',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q6Q759',
      gene: 'SPAG17',
      proteinName: 'Sperm-associated antigen 17',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q6S8J3',
      gene: 'POTEE',
      proteinName: 'POTE ankyrin domain family member E',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q6UWX4',
      gene: 'HHIPL2',
      proteinName: 'HHIP-like protein 2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q6UXL0',
      gene: 'IL20RB',
      proteinName: 'Interleukin-20 receptor subunit beta',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q6UXV0',
      gene: 'GFRAL',
      proteinName: 'GDNF family receptor alpha-like',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q6XPS3',
      gene: 'TPTE2',
      proteinName:
        'Phosphatidylinositol 3,4,5-trisphosphate 3-phosphatase TPTE2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q6ZMR5',
      gene: 'TMPRSS11A',
      proteinName: 'Transmembrane protease serine 11A',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q6ZRF8',
      gene: 'RNF207',
      proteinName: 'RING finger protein 207',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q6ZTR7',
      gene: 'FAM92B',
      proteinName: 'Protein FAM92B',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q76KP1',
      gene: 'B4GALNT4',
      proteinName:
        'N-acetyl-beta-glucosaminyl-glycoprotein 4-beta-N-acetylgalactosaminyltransferase 1',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q7RTV3',
      gene: 'ZNF367',
      proteinName: 'Zinc finger protein 367',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q7Z442',
      gene: 'PKD1L2',
      proteinName: 'Polycystic kidney disease protein 1-like 2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q7Z4W2',
      gene: 'LYZL2',
      proteinName: 'Lysozyme-like protein 2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q7Z6R9',
      gene: 'TFAP2D',
      proteinName: 'Transcription factor AP-2-delta',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q7Z7M9',
      gene: 'GALNT5',
      proteinName: 'Polypeptide N-acetylgalactosaminyltransferase 5',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q86SS6',
      gene: 'SYT9',
      proteinName: 'Synaptotagmin-9',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q86UX7',
      gene: 'FERMT3',
      proteinName: 'Fermitin family homolog 3',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q86WS4',
      gene: 'C12orf40',
      proteinName: 'Uncharacterized protein C12orf40',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q86Y46',
      gene: 'KRT73',
      proteinName: 'Keratin, type II cytoskeletal 73',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q86YM7',
      gene: 'HOMER1',
      proteinName: 'Homer protein homolog 1',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'Q86YR6',
      gene: 'POTED',
      proteinName: 'POTE ankyrin domain family member D',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q8IVH2',
      gene: 'FOXP4',
      proteinName: 'Forkhead box protein P4',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q8IVL1',
      gene: 'NAV2',
      proteinName: 'Neuron navigator 2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q8IZS5',
      gene: 'OFCC1',
      proteinName: 'Orofacial cleft 1 candidate gene 1 protein',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q8N0U7',
      gene: 'C1orf87',
      proteinName: 'Uncharacterized protein C1orf87',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q8N4T0',
      gene: 'CPA6',
      proteinName: 'Carboxypeptidase A6',
      reference: 'PMID: 28007376',
    },
    {
      uniprotID: 'Q8N5S9',
      gene: 'CAMKK1',
      proteinName: 'Calcium/calmodulin-dependent protein kinase kinase 1',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q8N690',
      gene: 'DEFB119',
      proteinName: 'Beta-defensin 119',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q8N6F1',
      gene: 'CLDN19',
      proteinName: 'Claudin-19',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q8N8Y5',
      gene: 'ZFP41',
      proteinName: 'Zinc finger protein 41 homolog',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q8N9W8',
      gene: 'FAM71D',
      proteinName: 'Protein FAM71D',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q8NA56',
      gene: 'TTC29',
      proteinName: 'Tetratricopeptide repeat protein 29',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q8NE65',
      gene: 'ZNF738',
      proteinName: 'Protein ZNF738',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q8NET8',
      gene: 'TRPV3',
      proteinName:
        'Transient receptor potential cation channel subfamily V member 3',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q8NHZ7',
      gene: 'MBD3L2',
      proteinName: 'Methyl-CpG-binding domain protein 3-like 2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q8TAU0',
      gene: 'NKX2-3',
      proteinName: 'Homeobox protein Nkx-2.3',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q8TAV4',
      gene: 'STOML3',
      proteinName: 'Stomatin-like protein 3',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q8TC56',
      gene: 'FAM71B',
      proteinName: 'Protein FAM71B',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q8TD06',
      gene: 'AGR3',
      proteinName: 'Anterior gradient protein 3',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q8TE58',
      gene: 'ADAMTS15',
      proteinName:
        'A disintegrin and metalloproteinase with thrombospondin motifs 15',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q8WU49',
      gene: 'C7orf33',
      proteinName: 'Uncharacterized protein C7orf33',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q8WWM1',
      gene: 'XAGE5',
      proteinName: 'X antigen family member 5',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q92796',
      gene: 'DLG3',
      proteinName: 'Disks large homolog 3',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'Q93088',
      gene: 'BHMT',
      proteinName: 'Betaine--homocysteine S-methyltransferase 1',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q969Q4',
      gene: 'ARL11',
      proteinName: 'ADP-ribosylation factor-like protein 11',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q969V4',
      gene: 'TEKT1',
      proteinName: 'Tektin-1',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q96A47',
      gene: 'ISL2',
      proteinName: 'Insulin gene enhancer protein ISL-2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q96EV2',
      gene: 'RBM33',
      proteinName: 'RNA-binding protein 33',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q96GL9',
      gene: 'FAM163A',
      proteinName: 'Protein FAM163A',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q96J92',
      gene: 'WNK4',
      proteinName: 'Serine/threonine-protein kinase WNK4',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q96LP2',
      gene: 'FAM81B',
      proteinName: 'Protein FAM81B',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q96LP6',
      gene: 'C12orf42',
      proteinName: 'Uncharacterized protein C12orf42',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q96M69',
      gene: 'LRGUK',
      proteinName:
        'Leucine-rich repeat and guanylate kinase domain-containing protein',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q96M86',
      gene: 'DNHD1',
      proteinName: 'Dynein heavy chain domain-containing protein 1',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q96MG2',
      gene: 'JSRP1',
      proteinName: 'Junctional sarcoplasmic reticulum protein 1',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q96N22',
      gene: 'ZNF681',
      proteinName: 'Zinc finger protein 681',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q96PI1',
      gene: 'SPRR4',
      proteinName: 'Small proline-rich protein 4',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q99593',
      gene: 'TBX5',
      proteinName: 'T-box transcription factor TBX5',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q99929',
      gene: 'ASCL2',
      proteinName: 'Achaete-scute homolog 2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q99999',
      gene: 'GAL3ST1',
      proteinName: 'Galactosylceramide sulfotransferase',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'Q9BX84',
      gene: 'TRPM6',
      proteinName:
        'Transient receptor potential cation channel subfamily M member 6',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9BXS0',
      gene: 'COL25A1',
      proteinName: 'Collagen alpha-1(XXV) chain',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9BXU1',
      gene: 'STK31',
      proteinName: 'Serine/threonine-protein kinase 31',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9BY21',
      gene: 'GPR87',
      proteinName: 'G-protein coupled receptor 87',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9BZD2',
      gene: 'SLC29A3',
      proteinName: 'Equilibrative nucleoside transporter 3',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9BZD6',
      gene: 'PRRG4',
      proteinName: 'Transmembrane gamma-carboxyglutamic acid protein 4',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9GZS0',
      gene: 'DNAI2',
      proteinName: 'Dynein intermediate chain 2, axonemal',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9GZY6',
      gene: 'LAT2',
      proteinName: 'Linker for activation of T-cells family member 2',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9H2U2',
      gene: 'PPA2',
      proteinName: 'Inorganic pyrophosphatase 2, mitochondrial',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9H329',
      gene: 'EPB41L4B',
      proteinName: 'Band 4.1-like protein 4B',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9H9D4',
      gene: 'ZNF408',
      proteinName: 'Zinc finger protein 408',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9HAZ2',
      gene: 'PRDM16',
      proteinName: 'Histone-lysine N-methyltransferase PRDM16',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9HB55',
      gene: 'CYP3A43',
      proteinName: 'Cytochrome P450 3A43',
      reference: 'PMID: 28276448',
    },
    {
      uniprotID: 'Q9HBB8',
      gene: 'CDHR5',
      proteinName: 'Cadherin-related family member 5',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9HCT0',
      gene: 'FGF22',
      proteinName: 'Fibroblast growth factor 22',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9NQ66',
      gene: 'PLCB1',
      proteinName:
        '1-phosphatidylinositol 4,5-bisphosphate phosphodiesterase beta-1',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'Q9NXI6',
      gene: 'RNF186',
      proteinName: 'E3 ubiquitin-protein ligase RNF186',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9NY43',
      gene: 'BARHL2',
      proteinName: 'BarH-like 2 homeobox protein',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9NY59',
      gene: 'SMPD3',
      proteinName: 'Sphingomyelin phosphodiesterase 3',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'Q9NZL3',
      gene: 'ZNF224',
      proteinName: 'Zinc finger protein 224',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9P219',
      gene: 'CCDC88C',
      proteinName: 'Protein Daple',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9UBR1',
      gene: 'UPB1',
      proteinName: 'Beta-ureidopropionase',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9UDY2',
      gene: 'TJP2',
      proteinName: 'Tight junction protein ZO-2',
      reference: 'PMID: 17515952',
    },
    {
      uniprotID: 'Q9UGF6',
      gene: 'OR5V1',
      proteinName: 'Olfactory receptor 5V1',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9UGP4',
      gene: 'LIMD1',
      proteinName: 'LIM domain-containing protein 1',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9UK17',
      gene: 'KCND3',
      proteinName: 'Potassium voltage-gated channel subfamily D member 3',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9UNW8',
      gene: 'GPR132',
      proteinName: 'Probable G-protein coupled receptor 132',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9Y574',
      gene: 'ASB4',
      proteinName: 'Ankyrin repeat and SOCS box protein 4',
      reference: 'PMID: 23483634',
    },
    {
      uniprotID: 'Q9Y6K8',
      gene: 'AK5',
      proteinName: 'Adenylate kinase isoenzyme 5',
      reference: 'PMID: 17515952',
    },
  ],
};

export default MtleJsonData;
