const MtleHsJsonData = {
  data: [
    {
      uniprotID: 'O95992',
      gene: 'CH25H',
      proteinName: 'Cholesterol 25-hydroxylase',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'P01011',
      gene: 'SERPINA3',
      proteinName: 'Alpha-1-antichymotrypsin',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'P01024',
      gene: 'C3',
      proteinName: 'Complement C3',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'P01100',
      gene: 'FOS',
      proteinName: 'Proto-oncogene c-Fos',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'P01213',
      gene: 'PDYN',
      proteinName: 'Proenkephalin-B',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'P01584',
      gene: 'IL1B',
      proteinName: 'Interleukin-1 beta',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'P01903',
      gene: 'HLA-DRA',
      proteinName: 'HLA class II histocompatibility antigen, DR alpha chain',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'P02042',
      gene: 'HBD',
      proteinName: 'Hemoglobin subunit delta',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'P02787',
      gene: 'TF',
      proteinName: 'Serotransferrin',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'P06241',
      gene: 'FYN',
      proteinName: 'Tyrosine-protein kinase Fyn',
      reference: 'PMID: 27094248',
    },
    {
      uniprotID: 'P12036',
      gene: 'NEFH',
      proteinName: 'Neurofilament heavy polypeptide',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'P13500',
      gene: 'CCL2',
      proteinName: 'C-C motif chemokine 2',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'P20036',
      gene: 'HLA-DPA1',
      proteinName: 'HLA class II histocompatibility antigen, DP alpha 1 chain',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'P20472',
      gene: 'PVALB',
      proteinName: 'Parvalbumin alpha',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'P34910',
      gene: 'EVI2B',
      proteinName: 'Protein EVI2B',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'P35414',
      gene: 'APLNR',
      proteinName: 'Apelin receptor',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'P37173',
      gene: 'TGFBR2',
      proteinName: 'TGF-beta receptor type-2',
      reference: 'PMID: 27094248',
    },
    {
      uniprotID: 'P49238',
      gene: 'CX3CR1',
      proteinName: 'CX3C chemokine receptor 1',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'P67870',
      gene: 'CSNK2B',
      proteinName: 'Casein kinase II subunit beta',
      reference: 'PMID: 27094248',
    },
    {
      uniprotID: 'P68871',
      gene: 'HBB',
      proteinName: 'Hemoglobin subunit beta',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'P78509',
      gene: 'RELN',
      proteinName: 'Reelin',
      reference: 'PMID: 27094248',
    },
    {
      uniprotID: 'Q07699',
      gene: 'SCN1B',
      proteinName: 'Sodium channel subunit beta-1',
      reference: 'PMID: 27094248   PMID: 30932156',
    },
    {
      uniprotID: 'Q08116',
      gene: 'RGS1',
      proteinName: 'Regulator of G-protein signaling 1',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'Q12840',
      gene: 'KIF5A',
      proteinName: 'Kinesin heavy chain isoform 5A',
      reference: 'PMID: 27094248',
    },
    {
      uniprotID: 'Q13571',
      gene: 'LAPTM5',
      proteinName: 'Lysosomal-associated transmembrane protein 5',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'Q14242',
      gene: 'SELPLG',
      proteinName: 'P-selectin glycoprotein ligand 1',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'Q7L5Y1',
      gene: 'ENOSF1',
      proteinName: 'Mitochondrial enolase superfamily member 1',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'Q86UW8',
      gene: 'HAPLN4',
      proteinName: 'Hyaluronan and proteoglycan link protein 4',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'Q8N9I0',
      gene: 'SYT2',
      proteinName: 'Synaptotagmin-2',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'Q8NFR3',
      gene: 'SPTSSB',
      proteinName: 'Serine palmitoyltransferase small subunit B',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'Q96NK8',
      gene: 'NEUROD6',
      proteinName: 'Neurogenic differentiation factor 6',
      reference: 'PMID: 27094248',
    },
    {
      uniprotID: 'Q9BPV8',
      gene: 'P2RY13',
      proteinName: 'P2Y purinoceptor 13',
      reference: 'PMID: 30932156',
    },
    {
      uniprotID: 'Q9BWW7',
      gene: 'SCRT1',
      proteinName: 'Transcriptional repressor scratch 1',
      reference: 'PMID: 27094248',
    },
    {
      uniprotID: 'Q9C000',
      gene: 'NLRP1',
      proteinName: 'NACHT, LRR and PYD domains-containing protein 1',
      reference: 'PMID: 27094248',
    },
    {
      uniprotID: 'Q9NZU7',
      gene: 'CABP1',
      proteinName: 'Calcium-binding protein 1',
      reference: 'PMID: 27094248',
    },
    {
      uniprotID: 'Q9UPC5',
      gene: 'GPR34',
      proteinName: 'Probable G-protein coupled receptor 34',
      reference: 'PMID: 30932156',
    },
  ],
};

export default MtleHsJsonData;
